# Generated by Django 4.0.3 on 2022-04-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_bike_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='type',
            field=models.CharField(choices=[('Mountain', 'Mountain'), ('Road', 'Road'), ('Gravel', 'Gravel')], default=('Mountain', 'Mountain'), max_length=8),
        ),
    ]
