# Generated by Django 4.0.3 on 2022-04-10 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_bike_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('task', models.CharField(choices=[('LC', 'Lube Chain'), ('WF', 'Wash Frame'), ('FT', 'Fill Tires'), ('CB', 'Check Bearings'), ('RB', 'Replace Brake Pads'), ('BW', 'Balance Wheels')], default='LC', max_length=2)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.bike')),
            ],
        ),
    ]
